theme: jekyll-theme-minimal
title: Mobile Muay Thai
description: intense workouts in your home or gym by Muay Thai pros
logo: assets/images/danielkerr.png
show_downloads: false
github:
  is_project_page: false
  is_user_page: false